//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_车辆报销明细
{
    public int ID { get; set; }
    public string 报销类型 { get; set; }
    public decimal 金额 { get; set; }
    public string 备注 { get; set; }
    public int 更新人ID { get; set; }
    public System.DateTime 更新时间 { get; set; }
    public int 车辆报销ID { get; set; }

    public virtual 财务_接待车辆报销 财务_接待车辆报销 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
}
