//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class HR_出差汇报
{
    public int ID { get; set; }
    public int 出差记录ID { get; set; }
    public int 出差关联计划项ID { get; set; }
    public Nullable<System.DateTime> 巡店开始时间 { get; set; }
    public string 工作成果 { get; set; }
    public string 实际遇到的问题 { get; set; }
    public string 解决的方案 { get; set; }
    public string 需要的协助 { get; set; }
    public Nullable<System.DateTime> 预计完成时间 { get; set; }
    public string 备注 { get; set; }
    public Nullable<bool> 是否包含附件 { get; set; }
    public Nullable<bool> 是否为新增项 { get; set; }
    public Nullable<System.DateTime> 提交时间 { get; set; }
    public Nullable<int> 提交人ID { get; set; }
    public Nullable<System.DateTime> 更新时间 { get; set; }
    public Nullable<int> 更新人ID { get; set; }
    public Nullable<System.DateTime> 巡店结束时间 { get; set; }

    public virtual HR_出差计划详细 HR_出差计划详细 { get; set; }
    public virtual HR_出差计划 HR_出差计划 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
