//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 营销_接待计划费用预估
{
    public int ID { get; set; }
    public string 摘要 { get; set; }
    public Nullable<decimal> 金额预估 { get; set; }
    public Nullable<System.DateTime> 时间 { get; set; }
    public Nullable<int> 接待计划ID { get; set; }

    public virtual 营销_接待计划 营销_接待计划 { get; set; }
}
