//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_核算分类
{
    public 财务_核算分类()
    {
        this.财务_其他报销_副表 = new HashSet<财务_其他报销_副表>();
    }

    public int ID { get; set; }
    public string 分类类型 { get; set; }
    public string 备注 { get; set; }

    public virtual ICollection<财务_其他报销_副表> 财务_其他报销_副表 { get; set; }
}
