//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 拓展_竞品档案表
{
    public 拓展_竞品档案表()
    {
        this.拓展_竞品档案_年销售档案表 = new HashSet<拓展_竞品档案_年销售档案表>();
    }

    public int ID { get; set; }
    public int 城市ID { get; set; }
    public Nullable<int> 商场ID { get; set; }
    public string 位置 { get; set; }
    public string 面积 { get; set; }
    public Nullable<System.DateTime> 入住日期 { get; set; }
    public Nullable<int> 经销商ID { get; set; }
    public Nullable<int> 录入人ID { get; set; }
    public Nullable<System.DateTime> 更新日期 { get; set; }
    public string 楼层 { get; set; }
    public string 经营形态 { get; set; }
    public string 备注 { get; set; }
    public string 折扣 { get; set; }
    public Nullable<int> 月店面客流 { get; set; }
    public string 形象 { get; set; }

    public virtual 拓展_城市档案 拓展_城市档案 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 拓展_商场档案表 拓展_商场档案表 { get; set; }
    public virtual 拓展_经销商档案表 拓展_经销商档案表 { get; set; }
    public virtual ICollection<拓展_竞品档案_年销售档案表> 拓展_竞品档案_年销售档案表 { get; set; }
}
