//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C5S_评审标准
{
    public int ID { get; set; }
    public string 评估项目 { get; set; }
    public string 具体内容 { get; set; }
    public string 评估标准 { get; set; }
    public Nullable<int> 分值 { get; set; }
    public string 扣分标准 { get; set; }
}
