//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class View__SPU
{
    public string 系列 { get; set; }
    public string 型号 { get; set; }
    public string 编号 { get; set; }
    public string 名称 { get; set; }
    public string 规格 { get; set; }
    public string 计量单位 { get; set; }
    public string SPU编号 { get; set; }
    public string SPU描述 { get; set; }
    public Nullable<int> 交货周期 { get; set; }
    public Nullable<bool> 是否进口 { get; set; }
    public Nullable<bool> 停用标志 { get; set; }
    public Nullable<bool> SPU停用标志 { get; set; }
    public int SPUID { get; set; }
    public Nullable<int> 商品ID { get; set; }
}
