//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 客服_售后分类
{
    public 客服_售后分类()
    {
        this.客服_售后费用分摊 = new HashSet<客服_售后费用分摊>();
        this.客服_售后费用分摊1 = new HashSet<客服_售后费用分摊>();
        this.客服_售后费用分摊2 = new HashSet<客服_售后费用分摊>();
        this.客服_售后跟进日志 = new HashSet<客服_售后跟进日志>();
        this.客服_售后跟进日志1 = new HashSet<客服_售后跟进日志>();
        this.客服_售后跟进日志2 = new HashSet<客服_售后跟进日志>();
    }

    public int ID { get; set; }
    public string 分类类型名称 { get; set; }
    public string 分类数据 { get; set; }
    public Nullable<bool> 是否停用 { get; set; }
    public Nullable<System.DateTime> 更新日期 { get; set; }
    public Nullable<int> 更新人 { get; set; }

    public virtual ICollection<客服_售后费用分摊> 客服_售后费用分摊 { get; set; }
    public virtual ICollection<客服_售后费用分摊> 客服_售后费用分摊1 { get; set; }
    public virtual ICollection<客服_售后费用分摊> 客服_售后费用分摊2 { get; set; }
    public virtual ICollection<客服_售后跟进日志> 客服_售后跟进日志 { get; set; }
    public virtual ICollection<客服_售后跟进日志> 客服_售后跟进日志1 { get; set; }
    public virtual ICollection<客服_售后跟进日志> 客服_售后跟进日志2 { get; set; }
}
