//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 拓展_城市档案
{
    public 拓展_城市档案()
    {
        this.拓展_竞品档案表 = new HashSet<拓展_竞品档案表>();
        this.拓展_商场档案表 = new HashSet<拓展_商场档案表>();
        this.拓展_经销商档案表 = new HashSet<拓展_经销商档案表>();
    }

    public int ID { get; set; }
    public string 省 { get; set; }
    public string 市 { get; set; }
    public string 城市分级 { get; set; }
    public Nullable<bool> 是否为目标城市 { get; set; }
    public int 录入人ID { get; set; }
    public Nullable<System.DateTime> 更新时间 { get; set; }

    public virtual 系统用户 系统用户 { get; set; }
    public virtual ICollection<拓展_竞品档案表> 拓展_竞品档案表 { get; set; }
    public virtual ICollection<拓展_商场档案表> 拓展_商场档案表 { get; set; }
    public virtual ICollection<拓展_经销商档案表> 拓展_经销商档案表 { get; set; }
}
