//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 系统用户_权限
{
    public int ID { get; set; }
    public int 功能ID { get; set; }
    public int 用户ID { get; set; }
    public bool 添加 { get; set; }
    public bool 修改 { get; set; }
    public bool 删除 { get; set; }
    public bool 查找 { get; set; }
    public bool 打印 { get; set; }
    public bool 审核 { get; set; }
    public bool 反审核 { get; set; }
}
