//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 系统功能
{
    public int ID { get; set; }
    public Nullable<int> F_ID { get; set; }
    public string 功能编号 { get; set; }
    public string 功能名称 { get; set; }
    public string 类别 { get; set; }
    public string FormName { get; set; }
    public string FunName { get; set; }
    public string Url { get; set; }
    public Nullable<bool> Is_BasicForm { get; set; }
    public Nullable<bool> Is_Menu { get; set; }
    public Nullable<bool> Is_OP { get; set; }
    public Nullable<int> 排序 { get; set; }
}
