//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 营销_接待来访主要事项
{
    public int ID { get; set; }
    public string 主要问题 { get; set; }
    public string 计划应对方案 { get; set; }
    public string 预计成果 { get; set; }
    public string 需要的协助 { get; set; }
    public Nullable<int> 接待计划ID { get; set; }

    public virtual 营销_接待计划 营销_接待计划 { get; set; }
}
