//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_接待车辆报销
{
    public 财务_接待车辆报销()
    {
        this.财务_车辆报销分摊 = new HashSet<财务_车辆报销分摊>();
        this.财务_车辆报销明细 = new HashSet<财务_车辆报销明细>();
    }

    public int ID { get; set; }
    public int 车辆数 { get; set; }
    public System.DateTime 用车开始时间 { get; set; }
    public System.DateTime 用车截止时间 { get; set; }
    public string 搭乘人员 { get; set; }
    public decimal 总计花费金额 { get; set; }
    public string 备注 { get; set; }
    public int 提交人ID { get; set; }
    public System.DateTime 提交时间 { get; set; }
    public int 更新人ID { get; set; }
    public System.DateTime 更新时间 { get; set; }
    public int 商务接待ID { get; set; }
    public Nullable<bool> 审核状态 { get; set; }
    public Nullable<int> 财务审核人ID { get; set; }

    public virtual ICollection<财务_车辆报销分摊> 财务_车辆报销分摊 { get; set; }
    public virtual ICollection<财务_车辆报销明细> 财务_车辆报销明细 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
    public virtual 营销_接待计划 营销_接待计划 { get; set; }
    public virtual 系统用户 系统用户2 { get; set; }
}
