//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_出差报销单
{
    public 财务_出差报销单()
    {
        this.财务_出差报销详细 = new HashSet<财务_出差报销详细>();
    }

    public int ID { get; set; }
    public Nullable<int> 关联出差ID { get; set; }
    public string 汇款银行 { get; set; }
    public string 汇款账号 { get; set; }
    public Nullable<decimal> 借款金额 { get; set; }
    public Nullable<decimal> 应退补金额 { get; set; }
    public Nullable<int> 报销人ID { get; set; }
    public Nullable<int> 部门ID { get; set; }
    public Nullable<System.DateTime> 提交时间 { get; set; }
    public Nullable<bool> 审核状态 { get; set; }
    public Nullable<int> 财务审核人ID { get; set; }
    public Nullable<decimal> 住宿费合计 { get; set; }
    public Nullable<decimal> 车船费合计 { get; set; }
    public Nullable<decimal> 交通费合计 { get; set; }
    public Nullable<decimal> 生活补助合计 { get; set; }
    public Nullable<decimal> 合计 { get; set; }
    public Nullable<bool> 是否作废 { get; set; }
    public string 户名 { get; set; }

    public virtual 系统_部门 系统_部门 { get; set; }
    public virtual ICollection<财务_出差报销详细> 财务_出差报销详细 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
