//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_机票明细分摊
{
    public int ID { get; set; }
    public Nullable<int> 机票明细ID { get; set; }
    public string 城市 { get; set; }
    public Nullable<decimal> 分摊金额 { get; set; }
    public string 备注 { get; set; }
}
