//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_接待住宿报销分摊
{
    public int ID { get; set; }
    public string 城市 { get; set; }
    public string 住宿人员 { get; set; }
    public string 住宿房间 { get; set; }
    public Nullable<decimal> 分摊金额 { get; set; }
    public string 对象类型 { get; set; }
    public Nullable<System.DateTime> 住宿开始时间 { get; set; }
    public Nullable<System.DateTime> 住宿截止时间 { get; set; }
    public string 备注 { get; set; }
    public Nullable<int> 提交人ID { get; set; }
    public Nullable<System.DateTime> 提交时间 { get; set; }
    public Nullable<int> 更新人ID { get; set; }
    public Nullable<System.DateTime> 更新时间 { get; set; }
    public Nullable<int> 接待住宿报销ID { get; set; }

    public virtual 财务_接待住宿报销 财务_接待住宿报销 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
