//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 销售_跟进目标数申请表
{
    public int ID { get; set; }
    public int 店铺ID { get; set; }
    public int 员工ID { get; set; }
    public int 申请跟进数 { get; set; }
    public Nullable<bool> 审核状态 { get; set; }
    public string 备注 { get; set; }
    public string 更新人 { get; set; }
    public Nullable<System.DateTime> 更新日期 { get; set; }

    public virtual 销售_店铺档案 销售_店铺档案 { get; set; }
}
