//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 销售_店铺员工档案
{
    public 销售_店铺员工档案()
    {
        this.客服_售后发起单 = new HashSet<客服_售后发起单>();
        this.销售_接待记录 = new HashSet<销售_接待记录>();
    }

    public int ID { get; set; }
    public int 店铺ID { get; set; }
    public string 编号 { get; set; }
    public string 姓名 { get; set; }
    public string 性别 { get; set; }
    public int 职务ID { get; set; }
    public string 等级 { get; set; }
    public string 联系方式 { get; set; }
    public bool 停用标志 { get; set; }
    public Nullable<int> 制单人 { get; set; }
    public Nullable<System.DateTime> 制单日期 { get; set; }
    public string 密码 { get; set; }
    public Nullable<int> 跟进目标计划数 { get; set; }
    public Nullable<bool> 是否销售 { get; set; }
    public Nullable<bool> 是否设计师 { get; set; }
    public Nullable<bool> 是否店长 { get; set; }

    public virtual ICollection<客服_售后发起单> 客服_售后发起单 { get; set; }
    public virtual ICollection<销售_接待记录> 销售_接待记录 { get; set; }
}
