//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 客服_售后跟进日志
{
    public int ID { get; set; }
    public int 营销售后ID { get; set; }
    public System.DateTime 日期 { get; set; }
    public int 跟进人ID { get; set; }
    public string 内容 { get; set; }
    public Nullable<int> 责任判定 { get; set; }
    public Nullable<decimal> 公司投入预估 { get; set; }
    public Nullable<decimal> 经销投入预估 { get; set; }
    public Nullable<decimal> 工厂投入预估 { get; set; }
    public Nullable<int> 问题分类 { get; set; }
    public Nullable<int> 材质分类 { get; set; }
    public Nullable<System.DateTime> 更新日期 { get; set; }
    public Nullable<int> 更新人 { get; set; }

    public virtual 客服_售后发起单 客服_售后发起单 { get; set; }
    public virtual 客服_售后分类 客服_售后分类 { get; set; }
    public virtual 客服_售后分类 客服_售后分类1 { get; set; }
    public virtual 客服_售后分类 客服_售后分类2 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
