//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_其它报销
{
    public 财务_其它报销()
    {
        this.财务_其他报销_副表 = new HashSet<财务_其他报销_副表>();
    }

    public int ID { get; set; }
    public Nullable<int> 报销部门ID { get; set; }
    public Nullable<int> 报销人ID { get; set; }
    public Nullable<System.DateTime> 提交日期 { get; set; }
    public Nullable<bool> 审核状态 { get; set; }
    public Nullable<int> 会计审核人ID { get; set; }
    public Nullable<decimal> 原借款 { get; set; }
    public Nullable<decimal> 应退余款 { get; set; }
    public string 汇款银行 { get; set; }
    public string 汇款银行卡账号 { get; set; }

    public virtual ICollection<财务_其他报销_副表> 财务_其他报销_副表 { get; set; }
    public virtual 系统_部门 系统_部门 { get; set; }
    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
