//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_收款单
{
    public int ID { get; set; }
    public string 付款方 { get; set; }
    public string 付款银行 { get; set; }
    public int 付款账号 { get; set; }
    public string 收款银行 { get; set; }
    public int 收款账号 { get; set; }
    public System.DateTime 付款时间 { get; set; }
    public Nullable<System.DateTime> 到账时间 { get; set; }
    public int 提交人 { get; set; }
    public System.DateTime 提交时间 { get; set; }
    public Nullable<int> 审核人 { get; set; }
    public Nullable<System.DateTime> 审核时间 { get; set; }
    public string 审核结果 { get; set; }
    public string 备注 { get; set; }
    public string 款项类型 { get; set; }
    public string 收款方 { get; set; }

    public virtual 系统用户 系统用户 { get; set; }
    public virtual 系统用户 系统用户1 { get; set; }
}
