//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 财务_其他报销_副表
{
    public int ID { get; set; }
    public Nullable<int> 其他报销ID { get; set; }
    public string 用途 { get; set; }
    public Nullable<int> 核算分类ID { get; set; }
    public Nullable<decimal> 金额 { get; set; }
    public Nullable<System.DateTime> 提交时间 { get; set; }

    public virtual 财务_核算分类 财务_核算分类 { get; set; }
    public virtual 财务_其它报销 财务_其它报销 { get; set; }
}
