//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 门店月报数据_Result
{
    public int 店铺ID { get; set; }
    public string 店铺名称 { get; set; }
    public int 面积 { get; set; }
    public Nullable<int> 客流量 { get; set; }
    public Nullable<int> 确认数 { get; set; }
    public string 确认率 { get; set; }
    public int 成交数 { get; set; }
    public string 成交率 { get; set; }
    public Nullable<decimal> 实际成交金额 { get; set; }
    public string 坪效 { get; set; }
    public Nullable<decimal> 自营业绩 { get; set; }
    public Nullable<decimal> 业务业绩 { get; set; }
    public string 平均单值 { get; set; }
    public Nullable<decimal> 最大单值 { get; set; }
    public Nullable<decimal> 实际订单金额 { get; set; }
    public Nullable<decimal> 预付款金额 { get; set; }
    public Nullable<decimal> 尾款 { get; set; }
    public Nullable<decimal> 总收款 { get; set; }
    public Nullable<decimal> 应下单金额 { get; set; }
    public Nullable<decimal> 下单率 { get; set; }
}
