//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 系统_部门
{
    public 系统_部门()
    {
        this.财务_出差报销单 = new HashSet<财务_出差报销单>();
        this.财务_其它报销 = new HashSet<财务_其它报销>();
    }

    public int ID { get; set; }
    public string 所属中心 { get; set; }
    public string 名称 { get; set; }
    public Nullable<int> 管理者 { get; set; }
    public Nullable<int> 上级ID { get; set; }

    public virtual ICollection<财务_出差报销单> 财务_出差报销单 { get; set; }
    public virtual ICollection<财务_其它报销> 财务_其它报销 { get; set; }
}
