//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 销售_接待记录_意向明细
{
    public int ID { get; set; }
    public int 接待ID { get; set; }
    public int 商品型号ID { get; set; }
    public string 备注 { get; set; }
    public string 空间 { get; set; }
}
