//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class View_销售成交记录
{
    public int 接待记录ID { get; set; }
    public string 客户姓名 { get; set; }
    public decimal 销售金额 { get; set; }
    public System.DateTime 销售日期 { get; set; }
    public string 店铺名称 { get; set; }
    public Nullable<int> 店铺ID { get; set; }
    public string 销售姓名 { get; set; }
    public int 销售人员ID { get; set; }
    public Nullable<bool> 是否业务业绩 { get; set; }
    public Nullable<bool> 是否自营业绩 { get; set; }
}
