//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 客服_售后发起单凭证
{
    public int ID { get; set; }
    public string 路径 { get; set; }
    public string 关联售后发起单号 { get; set; }
    public System.DateTime 时间 { get; set; }
    public int 提交人ID { get; set; }

    public virtual 系统用户 系统用户 { get; set; }
}
